apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx1
  namespace: nginx
spec:
  project: default
  source:
    chart: charts/nginx
    repoURL: https://github.com/oleksii-motonakha/argocd-demo
    targetRevision: master
    helm:
      valueFiles:
        - ../../manifests/cluster1/nginx1/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default